#------------Tetst 
#----first workflow
#----created by Denys Ponomarenko
name: MyFirstAction

on:
  push:
    branches: 
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello_world
      run: echo "Hello, world from testing !"
      
  my_deploy: 
     runs-on: ubuntu-latest
     steps:
       - name: Print second Hello world
         run: echo "Hello,world from deploy"
   
