#------------Tetst 
#----first workflow
#----created by Denys Ponomarenko
name: MyFirstAction
env:
  APPLICATION_NAME: "My flask"
  PACKAGE_NAME: "flask_ver_${{ github.sha }}"

on:
  push:
    branches: 
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latestfgg

    steps:
    - name: Print Hello_world
      run: echo "Hello, world from testing !"
    - name: Several commands execution
      run: |
        echo "Hello message 1"
        echo "Hello message 2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
        
    - name: Git clone my repo
      uses: actions/checkout@v1
      
    - name: List current folder
      run: ls -la
      
  my_deploy: 
     runs-on: ubuntu-latest
     needs: [my_testing]
     env:
       VAR1: "VAR1"
       VAR2: "VAR2"
     steps:
       - name: Print second Hello world
         run: echo "Hello,world from deploy"
       
       - name: Print variables
         run: |
           echo " VAR1 is : ${{ env.VAR1 }}"
           echo " VAR2 is : ${{ env.VAR2 }}" 
           echo " VAR3 is : $LOCAL_VAR"
         env: 
          LOCAL_VAR: "SUPER local VAr"
       
       - name: Print second env
         run: |
           echo "Package name: ${{ env.PACKAGE_NAME }}" 
           aws --version
           zip --version        
         
   
